const { GoogleGenerativeAI } = require('@google/generative-ai');
const fs = require('fs').promises;
const path = require('path');

const cachePath = path.join(__dirname, 'cache.json');
let cache = {};

const loadCache = async () => {
  try {
    const data = await fs.readFile(cachePath, 'utf8');
    cache = JSON.parse(data || '{}');
  } catch (error) {
    cache = {};
    await saveCache();
  }
};

const saveCache = async () => {
  await fs.writeFile(cachePath, JSON.stringify(cache, null, 2), 'utf8');
};

const normalizeSymptoms = (symptoms) => {
  return symptoms
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .replace(/[^a-z0-9 ,.-]/g, '');
};

const getCacheKey = (payload) => {
  const symptomText = normalizeSymptoms(payload.symptoms || '');
  const age = payload.age || 'unknown';
  const gender = (payload.gender || 'unknown').toLowerCase();
  return `${symptomText}|${age}|${gender}`;
};

const fallbackDiagnosis = (symptoms) => {
  const text = normalizeSymptoms(symptoms);

  if (text.includes('fever') && text.includes('cough')) {
    return {
      source: 'fallback',
      diagnosis: 'Likely viral illness such as flu or common cold. Recommend rest, fluids, and monitoring for worsening symptoms.',
      advice: 'If symptoms persist more than 3 days or breathing difficulty develops, seek medical evaluation.',
    };
  }

  if (text.includes('chest pain') || text.includes('pressure in chest') || text.includes('shortness of breath')) {
    return {
      source: 'fallback',
      diagnosis: 'Possible cardiac issue. This requires urgent medical evaluation.',
      advice: 'Refer the patient to emergency care immediately and obtain ECG and cardiac enzyme tests.',
    };
  }

  if (text.includes('headache') && text.includes('nausea')) {
    return {
      source: 'fallback',
      diagnosis: 'Symptoms are consistent with migraine. Consider lifestyle triggers and pain management.',
      advice: 'Recommend hydration, rest in a quiet dark room, and a migraine-specific analgesic if appropriate.',
    };
  }

  return null;
};

const callGeminiAPI = async (payload) => {
  if (!process.env.GEMINI_API_KEY) {
    throw new Error('Gemini API key is not configured.');
  }

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });

  const prompt = `
    You are MedisynX AI, a highly advanced clinical decision support assistant. 
    Analyze the following patient data and provide a professional, structured medical insight.
    
    PATIENT DATA:
    - Symptoms: ${payload.symptoms}
    - Age: ${payload.age || 'unknown'}
    - Gender: ${payload.gender || 'unknown'}
    - Medical History: ${payload.history || 'none'}
    
    RESPONSE FORMAT (Markdown):
    ### Potential Assessment
    [Brief overview of what these symptoms might indicate]
    
    ### Key Considerations
    - [List 2-3 important clinical points]
    
    ### Recommended Next Steps
    - [List 2-3 actionable steps for the clinician]
    
    ### Warning Signs
    - [List urgent symptoms that require immediate ER attention]
    
    Keep the tone professional and concise. Always include a disclaimer that this is an AI-assisted insight and not a final diagnosis.
  `;

  try {
    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error('Gemini API Error:', error);
    throw new Error('Failed to generate medical insight from AI service.');
  }
};

const getDiagnosis = async (payload) => {
  if (!payload.symptoms) {
    throw new Error('Symptoms are required for analysis.');
  }

  await loadCache();
  const cacheKey = getCacheKey(payload);

  if (cache[cacheKey]) {
    return { ...cache[cacheKey], cached: true };
  }

  // We still keep fallback for quick matches or offline-like behavior
  // but we prefer AI for more complex queries
  
  try {
    const diagnosisText = await callGeminiAPI(payload);
    const result = {
      source: 'gemini-1.5-flash',
      content: diagnosisText,
      disclaimer: 'This insight is generated by AI and should be reviewed by a qualified healthcare professional.',
      timestamp: new Date().toISOString(),
      cached: false,
    };
    cache[cacheKey] = result;
    await saveCache();
    return result;
  } catch (error) {
    const fallback = fallbackDiagnosis(payload.symptoms);
    if (fallback) {
      return { ...fallback, cached: false, source: 'fallback' };
    }
    
    return {
      source: 'error-handler',
      content: 'The AI service is currently experiencing high load. Please use clinical judgment.',
      disclaimer: 'AI service unavailable.',
      error: error.message,
      cached: false,
    };
  }
};

module.exports = {
  getDiagnosis,
};
